version: "3.8"
services:
  smartthings-cli:
    image: smartthings-cli
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ~/IdeaProjects/SmartthingsEdge:/SmartthingsEdge
#    environment:
#      - SMARTTHINGS_TOKEN=${SMARTTHINGS_TOKEN}
    build:
      context: .
      args:
        SMARTTHINGS_TOKEN: ${SMARTTHINGS_TOKEN}
    entrypoint: /bin/bash